### PR TITLE
631: (739?) Fix JSON output when -class is used and/or other weirdness.

### PR DESCRIPTION
**Pull request by wjblack**
This fix refactors all the if(func()=="")... duplicates to a series of
polymorphic JSON snippet generators.  It also sets up a small state tracker
for whether a comma should be prepended to the next entry (which fixes a bunch
of oddball cases where commas are missing or extraneous that was breaking
JSON format).  Since this code was adapted from asXML (which has no need to
track commas), it's likely that the bug was vestigal from assumptions made in
asXML().

Hopefully this both fixes all the JSON format issues and makes the code much
easier to maintain going forward.

### CODE REVIEW

**Comment by wjblack** [comment]
NB all that this is a release candidate to the upstream project, so it follows the upstream style as close as I could muster.  Style comments will probably be mocked.

**Comment by klaushofrichter** [comment]
Can we close this PR? It seems outdated.

**Comment by klaushofrichter** [comment]
@wjblack - I think we can close this PR?

**Comment by alzerid** [comment]
closed out of business scope

**Pull request closed without merging**
